import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { KeyRound, Lock, ShieldCheck, Target } from "lucide-react";
import { useState } from "react";
import { api } from "../api";
import { useAuth } from "../auth";
import { useI18n } from "../lib/i18n";
import { useToast } from "./Toast";
import { Button, Card, Field, inputClass, Spinner } from "./ui";
export function AccountSettings(){
 const {t}=useI18n();const toast=useToast();const {user,config,setUser,signOut}=useAuth();const qc=useQueryClient();
 const {data}=useQuery({queryKey:["workspace"],queryFn:api.workspace.get});
 const [key,setKey]=useState('');const [name,setName]=useState(user?.display_name??'');const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [confirm,setConfirm]=useState('');const [code,setCode]=useState('');const [goal,setGoal]=useState<number|null>(null);
 const fail=(e:Error)=>toast(e.message,'err');const refresh=()=>void qc.invalidateQueries({queryKey:["workspace"]});
 const saveKey=useMutation({mutationFn:()=>api.workspace.key(key),onSuccess:()=>{setKey('');refresh();toast(t('Apertus key saved'));},onError:fail});
 const removeKey=useMutation({mutationFn:api.workspace.removeKey,onSuccess:()=>{refresh();toast(t('Using the default Apertus key'));},onError:fail});
 const rename=useMutation({mutationFn:()=>api.me.update({display_name:name}),onSuccess:u=>{setUser(u);toast(t('Saved'));},onError:fail});
 const password=useMutation({mutationFn:()=>api.workspace.password(current,next),onSuccess:async()=>{toast(t('Password changed. Please sign in again.'));await signOut();},onError:fail});
 const recovery=useMutation({mutationFn:api.workspace.recoveryCode,onSuccess:r=>setCode(r.code),onError:fail});
 const notifications=useMutation({mutationFn:async()=>{
   if(data?.push_enabled){await api.workspace.disablePush();const registration=await navigator.serviceWorker.getRegistration();await (await registration?.pushManager.getSubscription())?.unsubscribe();return;}
   const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error(t("Notifications were not enabled"));
   const registration=await navigator.serviceWorker.register('/sw.js');await navigator.serviceWorker.ready;
   const raw=atob((config?.push_public_key??'').replace(/-/g,'+').replace(/_/g,'/'));
   const applicationServerKey=Uint8Array.from(raw,c=>c.charCodeAt(0));
   const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey});
   await api.workspace.push(subscription.toJSON());
 },onSuccess:()=>{refresh();toast(t("Saved"));},onError:fail});
 const preferences=useMutation({mutationFn:()=>api.workspace.preferences({weekly_goal:goal??data?.weekly_goal??3,tour_complete:data?.tour_complete??true}),onSuccess:()=>{refresh();toast(t('Saved'));},onError:fail});
 return <>{config?.push_public_key&&'serviceWorker' in navigator&&'PushManager' in window&&<Card className="p-6"><h2 className="font-display text-lg font-bold">{t('Follow-up notifications')}</h2><p className="my-3 text-sm text-ink-2">{t('An hourly scan checks your applications. Turn on browser notifications to hear when a new follow-up is ready, even with this tab closed.')}</p><Button variant="outline" disabled={notifications.isPending} onClick={()=>notifications.mutate()}>{t(data?.push_enabled?'Turn off notifications':'Enable notifications')}</Button></Card>}<Card className="p-6"><h2 className="mb-4 flex items-center gap-2 font-display text-lg font-bold"><ShieldCheck size={18} className="text-lake"/>{t('Account details')}</h2><form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();rename.mutate();}}><Field label={t('First name or nickname')}><input className={inputClass} value={name} onChange={e=>setName(e.target.value)} maxLength={60} required/></Field><Button variant="primary" disabled={!name.trim()||rename.isPending}>{t('Save name')}</Button></form><p className="mt-3 text-xs text-ink-3">{t('Your username stays the same. No email or phone number is required.')}</p></Card>
 <Card className="p-6"><h2 className="mb-3 flex items-center gap-2 font-display text-lg font-bold"><KeyRound size={18} className="text-lake"/>{t('Apertus connection')}</h2><p className="mb-5 text-sm leading-relaxed text-ink-2">{t('Apertus 1.5 8B is ready to use with the default server key. Optionally add your own Hack Apertus key. The model and endpoint stay fixed. Your key is encrypted and is never returned to the browser.')}</p><p className="mb-4 rounded-xl bg-sign/60 px-4 py-3 text-sm font-semibold text-lake">{data?.key_configured?t('Personal Apertus key')+' '+data.key_hint:t('Default Apertus key active')}</p><form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();saveKey.mutate();}}><Field label={t('Personal Apertus API key')}><input className={inputClass} type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="sk-..." required/></Field><Button variant="primary" disabled={key.length<8||saveKey.isPending}>{saveKey.isPending?<Spinner/>:null}{t('Validate & save')}</Button>{data?.key_configured&&<Button type="button" disabled={removeKey.isPending} onClick={()=>removeKey.mutate()}>{t('Use default key')}</Button>}</form></Card>
 <Card className="p-6"><h2 className="mb-4 flex items-center gap-2 font-display text-lg font-bold"><Target size={18} className="text-lake"/>{t('Your weekly practice goal')}</h2><form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();preferences.mutate();}}><Field label={t('Interviews per week')}><input className={`${inputClass} max-w-32`} type="number" min={1} max={30} value={goal??data?.weekly_goal??3} onChange={e=>setGoal(Number(e.target.value))}/></Field><Button variant="primary" disabled={preferences.isPending}>{t('Save goal')}</Button></form></Card>
 <Card className="p-6"><h2 className="mb-4 flex items-center gap-2 font-display text-lg font-bold"><Lock size={18} className="text-lake"/>{t('Password & recovery')}</h2><form className="grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();password.mutate();}}><Field label={t('Current password')}><input type="password" autoComplete="current-password" className={inputClass} value={current} onChange={e=>setCurrent(e.target.value)} required/></Field><Field label={t('New password')}><input type="password" autoComplete="new-password" className={inputClass} minLength={8} value={next} onChange={e=>setNext(e.target.value)} required/></Field><Field label={t('Confirm new password')}><input type="password" autoComplete="new-password" className={inputClass} minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></Field><div className="flex items-end"><Button variant="primary" disabled={next.length<8||next!==confirm||!current||password.isPending}>{t('Change password')}</Button></div></form><div className="mt-6 border-t border-line-soft pt-5"><p className="mb-3 text-sm text-ink-2">{t('Save a recovery code somewhere safe. It lets you reset your password without sharing an email address. Generating a new code replaces the previous one.')}</p><Button variant="outline" disabled={recovery.isPending} onClick={()=>recovery.mutate()}>{t('Generate recovery code')}</Button>{code&&<div className="mt-3 rounded-xl bg-raised p-4"><p className="mb-2 text-xs text-ink-3">{t('Shown only now. Save it before leaving this page.')}</p><code className="break-all text-sm">{code}</code></div>}</div></Card></>;
}
