import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useLocation, Link } from "react-router-dom";
import { Check, Copy, Download, FileUp, Mail, RefreshCw, Sparkles, TrendingUp } from "lucide-react";
import { api, type OutreachDraft } from "../api";
import { PageHeader } from "../components/Shell";
import { Button, Card, EmptyState, Field, inputClass, Spinner } from "../components/ui";
import { useToast } from "../components/Toast";
import { useI18n } from "../lib/i18n";

export default function WorkspacePage(){
 const {t}=useI18n(); const route=useLocation().pathname; const qc=useQueryClient(); const toast=useToast();
 const {data:workspace,isError,error}=useQuery({queryKey:["workspace"],queryFn:api.workspace.get});
 const {data:apps}=useQuery({queryKey:["applications"],queryFn:api.applications.list});
 const {data:analytics}=useQuery({queryKey:["application-analytics"],queryFn:api.workspace.analytics,enabled:route==='/analytics'});
 const [application,setApplication]=useState(''); const [kind,setKind]=useState('cover_letter'); const [csv,setCsv]=useState(''); const [importKind,setImportKind]=useState('applications'); const [result,setResult]=useState<{imported:number;errors:{row:number;reason:string}[]}|null>(null);
 const refresh=()=>{void qc.invalidateQueries({queryKey:["workspace"]});void qc.invalidateQueries({queryKey:["applications"]});void qc.invalidateQueries({queryKey:["application-analytics"]});};
 const fail=(e:Error)=>toast(e.message,'err');
 const generate=useMutation({mutationFn:()=>api.workspace.generate({application_id:application||apps?.[0]?.id||'',kind}),onSuccess:()=>{refresh();toast(t('Draft ready'));},onError:fail});
 const scan=useMutation({mutationFn:api.workspace.scan,onSuccess:()=>{refresh();toast(t('Scan complete'));},onError:fail});
 const upload=useMutation({mutationFn:()=>api.workspace.import({contents:csv,kind:importKind}),onSuccess:r=>{setResult(r);refresh();},onError:fail});
 const finish=useMutation({mutationFn:api.workspace.done,onSuccess:refresh,onError:fail});
 const download=async(kind:string)=>{try{await api.workspace.download(kind);}catch(e){fail(e as Error);}};
 const title=route==='/nudges'?'Never lose the conversation':route==='/import'?'Your search comes with you':route==='/analytics'?'See your search clearly':'Your voice. A little support.';
 if(isError)return <div className="p-8"><p>{error.message}</p><Button onClick={refresh}>{t('Try again')}</Button></div>;
 return <div className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><PageHeader eyebrow={t(route==='/nudges'?'Follow-up inbox':route==='/import'?'Import & export':route==='/analytics'?'Application insights':'Apertus writing studio')} title={t(title)} sub={t('Built around your real experiences. Always review before you send.')}/>
 {route==='/outreach'&&<><Card className="mb-6 grid items-end gap-4 p-5 sm:grid-cols-[1fr_1fr_auto]"><Field label={t('Apprenticeship')}><select className={inputClass} value={application||apps?.[0]?.id||''} onChange={e=>setApplication(e.target.value)}>{apps?.map(a=><option value={a.id} key={a.id}>{a.company}</option>)}</select></Field><Field label={t('What would you like to write?')}><select className={inputClass} value={kind} onChange={e=>setKind(e.target.value)}>{[['cover_letter','Cover letter'],['follow_up','Follow-up email'],['referral','Referral request'],['linkedin','LinkedIn message'],['thank_you','Thank-you note'],['prep','Interview prep pack']].map(([v,l])=><option key={v} value={v}>{t(l)}</option>)}</select></Field><Button variant="primary" disabled={!apps?.length||generate.isPending} onClick={()=>generate.mutate()}>{generate.isPending?<Spinner/>:<Sparkles size={16}/>} {t('Create with Apertus')}</Button></Card><div className="space-y-5">{workspace?.drafts.slice().reverse().map(d=><DraftEditor key={d.id} draft={d} refresh={refresh}/>)}{workspace&&!workspace.drafts.length&&<EmptyState title={t('Your first draft starts here')} hint={t('Choose an apprenticeship above. Add stories to your profile for more personal drafts.')} icon={<Mail/>} action={!apps?.length?<Link to="/applications"><Button variant="primary">{t('Add apprenticeship')}</Button></Link>:undefined}/>}</div></>}
 {route==='/nudges'&&<><Card className="mb-6 flex flex-wrap items-center justify-between gap-4 p-5"><div><h2 className="font-bold">{t('A thoughtful follow-up goes a long way')}</h2><p className="mt-1 max-w-xl text-sm text-ink-2">{t('Quiet applications get reminders after 5, 12 and 22 days. Past interviews get thank-you drafts. A scan never duplicates a reminder.')}</p></div><Button variant="primary" disabled={scan.isPending} onClick={()=>scan.mutate()}>{scan.isPending?<Spinner/>:<RefreshCw size={16}/>} {t('Scan now')}</Button></Card><div className="space-y-4">{workspace?.nudges.filter(n=>!n.done).map(n=><Card key={n.id} className="p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">{n.company}</h2><p className="text-sm text-ink-3">{t(n.kind.startsWith('follow_up')?'Time to follow up':'A thank-you note')}</p></div><Button variant="outline" disabled={finish.isPending} onClick={()=>finish.mutate(n.id)}><Check size={16}/>{t('Mark done')}</Button></div>{workspace.drafts.find(d=>d.id===n.draft_id)&&<DraftEditor draft={workspace.drafts.find(d=>d.id===n.draft_id)!} refresh={refresh}/>}</Card>)}{workspace&&!workspace.nudges.some(n=>!n.done)&&<EmptyState title={t('All caught up')} hint={t('Run a scan to check your applications. Your reminders will appear here.')} icon={<Check/>}/>}</div></>}
 {route==='/import'&&<div className="grid gap-6 lg:grid-cols-2"><Card className="p-6"><h2 className="mb-4 font-display text-xl font-bold">{t('Bring your applications')}</h2><p className="mb-4 text-sm text-ink-2">{t('Upload CSV from a spreadsheet, Teal or Huntr. Company and status columns are supported. Re-importing updates existing rows instead of duplicating them.')}</p><Field label={t('Dataset')}><select className={inputClass} value={importKind} onChange={e=>setImportKind(e.target.value)}><option value="applications">{t('Applications')}</option><option value="drafts">{t('Drafts')}</option></select></Field><input aria-label={t('Upload CSV')} type="file" accept=".csv,text/csv" className="my-4 block max-w-full text-sm file:mr-3 file:rounded-lg file:border-0 file:bg-sign file:px-4 file:py-2 file:text-lake" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>500000){toast(t('File is too large'),'err');return;}setCsv(await f.text());setResult(null);}}}/><Field label={t('CSV preview')}><textarea className={`${inputClass} min-h-40 font-mono text-xs`} value={csv} onChange={e=>setCsv(e.target.value)} placeholder="id,company,title,status,description"/></Field><div className="mt-4 flex gap-2"><Button variant="primary" onClick={()=>upload.mutate()} disabled={!csv.trim()||upload.isPending}>{upload.isPending?<Spinner/>:<FileUp size={16}/>} {t('Run import')}</Button><Button onClick={()=>setCsv(importKind==='applications'?'id,company,title,status,description\nsample-1,Calanda Care,Healthcare apprentice,applied,Support residents during daily care':'id,jobId,type,contents,status\ndraft-1,sample-1,follow_up,"Hello, I would like to ask about my application.",draft')}>{t('Load sample')}</Button></div>{result&&<div className="mt-4 rounded-xl bg-raised p-4 text-sm" role="status"><p>{result.imported} {t('rows imported')}</p>{result.errors.map(e=><p key={e.row} className="mt-2 text-blaze">{t('Row')} {e.row}: {e.reason}</p>)}</div>}</Card><Card className="h-fit p-6"><h2 className="font-display text-xl font-bold">{t('Your data belongs to you')}</h2><p className="mt-3 text-sm text-ink-2">{t('Download your applications and drafts as CSV. A complete account export is available in Profile & privacy.')}</p><div className="mt-5 flex flex-wrap gap-3"><Button variant="outline" onClick={()=>void download('applications')}><Download size={16}/>{t('Applications CSV')}</Button><Button variant="outline" onClick={()=>void download('drafts')}><Download size={16}/>{t('Drafts CSV')}</Button></div></Card></div>}
 {route==='/analytics'&&analytics&&<><div className="mb-6 grid grid-cols-2 gap-4 lg:grid-cols-4">{[['Interview rate',analytics.interview_rate+'%'],['Offer rate',analytics.offer_rate+'%'],['Quiet applications',analytics.quiet_rate+'%'],['Median days to interview',analytics.median_days_to_interview??'–']].map(([l,v])=><Card key={l} className="p-5"><TrendingUp size={18} className="text-lake"/><p className="mt-4 font-display text-3xl font-bold">{v}</p><p className="mt-2 text-xs text-ink-3">{t(String(l))}</p></Card>)}</div><div className="grid gap-6 lg:grid-cols-2"><Card className="p-6"><h2 className="mb-5 font-bold">{t('Application funnel')}</h2>{Object.entries(analytics.stages).map(([stage,n])=><div key={stage} className="mb-4"><div className="mb-1.5 flex justify-between text-sm"><span>{t(stage)}</span><span className="font-semibold">{n}</span></div><div className="h-3 rounded-full bg-raised"><div className="h-full rounded-full bg-lake" style={{width:`${analytics.total?100*n/analytics.total:0}%`}}/></div></div>)}</Card><Card className="p-6"><h2 className="mb-5 font-bold">{t('Weekly momentum')}</h2><div className="flex h-52 items-end justify-around gap-3">{analytics.weekly.map(w=><div key={w.week} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><span className="text-sm font-bold">{w.applications}</span><div className="w-full max-w-12 rounded-t-lg bg-lake/80" style={{height:`${Math.max(4,150*w.applications/Math.max(1,...analytics.weekly.map(w=>w.applications)))}px`}}/><span className="text-[11px] text-ink-3">{w.week}</span></div>)}</div><p className="mt-6 text-xs text-ink-3">{t('Rates use applications that reached the applied stage. Quiet means no stage update for 14 days.')}</p></Card></div></>}
 {!workspace&&<Spinner/>}</div>;
}
function DraftEditor({draft,refresh}:{draft:OutreachDraft;refresh:()=>void}){
 const {t}=useI18n();const toast=useToast();const [contents,setContents]=useState(draft.contents);const [subject,setSubject]=useState(draft.subject);const [recipient,setRecipient]=useState('');
 const save=useMutation({mutationFn:(status?:string)=>api.workspace.updateDraft(draft.id,{contents,subject,...(status?{status}:{})}),onSuccess:()=>{refresh();toast(t('Saved'));},onError:e=>toast(e.message,'err')});
 return <Card className="p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><div><p className="font-bold">{draft.company}</p><p className="mt-1 text-xs text-ink-3">{t(draft.kind.replaceAll('_',' '))} · {draft.model} · {t(draft.status==='sent'?'Marked sent':'Draft')}</p></div><span className="rounded-full bg-sign px-3 py-1 text-xs font-semibold text-lake">{t(draft.fallback?'Editable template':'Written with Apertus')}</span></div><Field label={t('Subject')}><input className={inputClass} value={subject} onChange={e=>setSubject(e.target.value)} maxLength={250}/></Field><textarea aria-label={t('Draft contents')} className={`${inputClass} mt-3 min-h-48 text-sm leading-relaxed`} value={contents} onChange={e=>setContents(e.target.value)} maxLength={12000}/><p className="mt-3 text-xs text-ink-3">{t('Grounded in')}: {draft.sources.map(s=>t(s)).join(' · ')}</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="primary" disabled={save.isPending} onClick={()=>save.mutate(undefined)}>{t('Save draft')}</Button><Button variant="outline" onClick={()=>void navigator.clipboard.writeText(contents).then(()=>toast(t('Copied'))).catch(()=>toast(t('Could not copy'),'err'))}><Copy size={14}/>{t('Copy')}</Button><Button variant="outline" disabled={save.isPending||draft.status==='sent'} onClick={()=>save.mutate('sent')}><Check size={14}/>{t('Mark sent')}</Button></div>{draft.kind!=='prep'&&<div className="mt-4 flex flex-wrap items-center gap-2"><input aria-label={t('Recipient email')} type="email" className={`${inputClass} max-w-xs`} placeholder="name@example.com" value={recipient} onChange={e=>setRecipient(e.target.value)}/><a className="text-sm font-semibold text-lake underline" href={`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(recipient)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(contents)}`} target="_blank" rel="noreferrer">{t('Review in Gmail')}</a></div>}<p className="mt-3 text-xs text-ink-3">{t('Nothing is sent automatically. Check every fact and personalize your message.')}</p></Card>;
}
