/** UI translations. Keys are the English source strings used with t("…"). */
import type { Lang } from "../types";

export const STRINGS: Partial<Record<Lang, Record<string, string>>> = {
  de: {
    "Welcome to Zusage, {name}!": "Willkommen bei Zusage, {name}!",
    "Three quick questions so your interviewer can ask about YOU. No addresses or phone numbers needed.": "Drei kurze Fragen, damit dein Gegenüber im Gespräch nach DIR fragen kann. Keine Adressen oder Telefonnummern nötig.",
    "Separate with commas": "Mit Kommas trennen",
    "One moment you're proud of": "Ein Moment, auf den du stolz bist",
    "A problem you solved or a time you helped someone - great material for answers.": "Ein Problem, das du gelöst hast, oder eine Situation, in der du jemandem geholfen hast – super Material für Antworten.",
    "Skip for now": "Jetzt überspringen",
    "Next": "Weiter",
    "Let's go": "Los geht's",
    "2 years · Federal VET Certificate": "2 Jahre · Berufsattest",
    "3–4 years · Federal VET Diploma": "3–4 Jahre · Fähigkeitszeugnis",
    "(deleted after the retention period)": "(nach Ablauf der Aufbewahrungsfrist gelöscht)",
    "10 questions · about 15 min": "10 Fragen · ca. 15 Min.",
    "2 min": "2 Min.",
    "5 questions · about 6 min": "5 Fragen · ca. 6 Min.",
    "A drill moves up a box when you answer it well, and back to box 1 when not.": "Ein Kurztraining rückt eine Box vor, wenn du es gut beantwortest – sonst geht es zurück in Box 1.",
    "A real experience (e.g. trial apprenticeship)": "Ein echtes Erlebnis (z. B. Schnupperlehre)",
    "A structure that works:": "Ein Aufbau, der funktioniert:",
    "About you": "Über dich",
    "Add a hobby + Enter": "Hobby eingeben + Enter",
    "Add a story": "Geschichte hinzufügen",
    "Add an apprenticeship": "Lehrstelle hinzufügen",
    "Add apprenticeship": "Lehrstelle hinzufügen",
    "After each interview, your weakest answers come back here after 1, 3 and 7 days.": "Nach jedem Gespräch kommen deine schwächsten Antworten nach 1, 3 und 7 Tagen hierher zurück.",
    "Age": "Alter",
    "All interviews": "Alle Gespräche",
    "Answer by answer": "Antwort für Antwort",
    "Answer in dialect or standard German…": "Antworte in Mundart oder Hochdeutsch…",
    "Answer, see what worked, try again right away. Weak answers come back as 2-minute drills on day 1, 3 and 7 - spaced practice, like learning vocabulary.": "Antworten, sehen, was funktioniert hat, gleich nochmals versuchen. Schwache Antworten kommen an Tag 1, 3 und 7 als 2-Minuten-Kurztrainings zurück – verteiltes Üben, wie beim Wörtilernen.",
    "Answers private - you see scores and goals only.": "Antworten privat – Sie sehen nur Punkte und Ziele.",
    "Applications": "Bewerbungen",
    "Applications in the class": "Bewerbungen in der Klasse",
    "Applied": "Beworben",
    "Apprenticeship": "Lehrstelle",
    "Apprenticeship added": "Lehrstelle hinzugefügt",
    "At least 8 characters.": "Mindestens 8 Zeichen.",
    "Back to class": "Zurück zur Klasse",
    "Back to today": "Zurück zu Heute",
    "Based on your words:": "Aus deinen Worten:",
    "Best moment:": "Bester Moment:",
    "Beta · type in dialect": "Beta · Mundart schreiben",
    "Box {n}": "Box {n}",
    "Breathe in for 4 seconds, out for 6. Then answer the first sentence slowly.": "4 Sekunden einatmen, 6 ausatmen. Dann den ersten Satz langsam beantworten.",
    "Built for Hack Apertus 2026 · FHGR challenge · Apache-2.0": "Entwickelt für Hack Apertus 2026 · FHGR-Challenge · Apache-2.0",
    "Can I do the vocational baccalaureate (BM)?": "Kann ich die Berufsmaturität (BM) machen?",
    "Can't reach the Zusage server": "Zusage-Server nicht erreichbar",
    "Cancel": "Abbrechen",
    "Check in with:": "Nachfragen bei:",
    "Choose an apprenticeship first.": "Wähle zuerst eine Lehrstelle.",
    "Choose what feels right today. You can always pause, retry an answer or stop early.": "Wähle, was sich heute richtig anfühlt. Du kannst jederzeit pausieren, eine Antwort wiederholen oder früher aufhören.",
    "Clarity": "Klarheit",
    "Class": "Klasse",
    "Class code": "Klassencode",
    "Class code (optional)": "Klassencode (optional)",
    "Class code not found": "Klassencode nicht gefunden",
    "Class name": "Name der Klasse",
    "Class profile": "Klassenprofil",
    "Coach feedback": "Coach-Feedback",
    "Coach model": "Coach-Modell",
    "Coach tips after every answer, retry allowed": "Coach-Tipps nach jeder Antwort, Wiederholen erlaubt",
    "Coach: Apertus": "Coach: Apertus",
    "Code copied": "Code kopiert",
    "Communication": "Kommunikation",
    "Company": "Betrieb",
    "Company research sprint: 10 minutes on the company website, note 2 facts to mention in the interview.": "Firmen-Recherche-Sprint: 10 Minuten auf der Website des Betriebs, 2 Fakten notieren, die man im Gespräch erwähnen kann.",
    "Complete": "Komplett",
    "Concrete examples": "Konkrete Beispiele",
    "Confidence before → after": "Selbstvertrauen vorher → nachher",
    "Confidence {n} of 5": "Selbstvertrauen {n} von 5",
    "Congratulations on your offer! 🎉": "Herzliche Gratulation zur Zusage! 🎉",
    "Contact person": "Ansprechperson",
    "Continue": "Weiter",
    "Continue practising": "Weiter üben",
    "Copy": "Kopieren",
    "Could not move the card - try again.": "Karte konnte nicht verschoben werden – versuch es nochmals.",
    "Could not save - check the fields.": "Speichern fehlgeschlagen – prüf die Felder.",
    "Could not start the interview.": "Das Gespräch konnte nicht gestartet werden.",
    "Create account": "Konto erstellen",
    "Create class": "Klasse erstellen",
    "Create your first class": "Erstellen Sie Ihre erste Klasse",
    "Criteria (last 3 interviews)": "Kriterien (letzte 3 Gespräche)",
    "Delete my account": "Mein Konto löschen",
    "Delete permanently": "Endgültig löschen",
    "Delete your account?": "Konto löschen?",
    "Demo accounts with a fictional class - no sign-up needed.": "Demo-Konten mit einer fiktiven Klasse – ohne Registrierung.",
    "Dictate (uses your browser's speech recognition)": "Diktieren (nutzt die Spracherkennung deines Browsers)",
    "Difficulty {n} of 3": "Schwierigkeit {n} von 3",
    "Download my data": "Meine Daten herunterladen",
    "Dream apprenticeship": "Traumlehrstelle",
    "Dress rehearsal": "Hauptprobe",
    "Drill": "Kurztraining",
    "Due today · spaced practice": "Heute fällig · verteiltes Üben",
    "Every comment quotes your own words, scored on six criteria from Swiss vocational education. No grades, no shaming - one concrete next step.": "Jeder Kommentar zitiert deine eigenen Worte, bewertet nach sechs Kriterien aus der Schweizer Berufsbildung. Keine Noten, kein Blossstellen – ein konkreter nächster Schritt.",
    "Every practice interview, drill and retry - measured on the same six criteria.": "Jedes Übungsgespräch, Kurztraining und jede Wiederholung – gemessen an denselben sechs Kriterien.",
    "Example of a practice interview": "Beispiel eines Übungsgesprächs",
    "Feedback you can trust": "Feedback, dem du vertrauen kannst",
    "Finish": "Beenden",
    "Finish a practice interview to see your profile here.": "Schliesse ein Übungsgespräch ab, um hier dein Profil zu sehen.",
    "Finish the interview?": "Gespräch beenden?",
    "First attempt:": "Erster Versuch:",
    "First name or nickname": "Vorname oder Spitzname",
    "Five questions, about six minutes. Your coach shows you what already works.": "Fünf Fragen, etwa sechs Minuten. Dein Coach zeigt dir, was schon gut klappt.",
    "Focus": "Fokus",
    "For a real application? (optional)": "Für eine echte Bewerbung? (optional)",
    "From your story bank": "Aus deiner Geschichtensammlung",
    "From your teacher. You can add it later.": "Von deiner Lehrperson. Du kannst ihn später hinzufügen.",
    "General practice": "Allgemeines Training",
    "Give an example": "Gib ein Beispiel",
    "Good questions to ask:": "Gute Fragen zum Stellen:",
    "Goodbye": "Tschüss",
    "Guess first - then compare with your coach. This trains your inner judge.": "Zuerst schätzen – dann mit dem Coach vergleichen. So trainierst du dein inneres Urteil.",
    "Headline first: answer any question in one sentence, then add one reason. Practise with a timer (30 s).": "Kernaussage zuerst: jede Frage in einem Satz beantworten, dann einen Grund ergänzen. Mit Timer üben (30 s).",
    "Hello {name}!": "Hallo {name}!",
    "Hide": "Ausblenden",
    "Hide answers": "Antworten ausblenden",
    "Hide example": "Beispiel ausblenden",
    "Hide hint": "Tipp ausblenden",
    "Hint": "Tipp",
    "Hobbies": "Hobbys",
    "How confident do you feel about job interviews now?": "Wie sicher fühlst du dich jetzt bei Vorstellungsgesprächen?",
    "How confident do you feel about job interviews right now?": "Wie sicher fühlst du dich gerade bei Vorstellungsgesprächen?",
    "How did that answer go?": "Wie lief diese Antwort?",
    "How far you've come": "So weit bist du gekommen",
    "How it could sound": "So könnte es klingen",
    "How it helps in the job": "Wie es im Beruf hilft",
    "I'm a student": "Ich bin Schüler:in",
    "I'm a teacher": "Ich bin Lehrperson",
    "I'm stuck - give me a hint": "Ich hänge – gib mir einen Tipp",
    "In {n} days": "In {n} Tagen",
    "Interested": "Interessiert",
    "Interview": "Gespräch",
    "Interview at {company}": "Gespräch bei {company}",
    "Interview coach for your apprenticeship": "Gesprächscoach für deine Lehrstelle",
    "Interview completed": "Gespräch abgeschlossen",
    "Interview date": "Gesprächstermin",
    "Interview finished!": "Gespräch geschafft!",
    "Interview in progress": "Gespräch läuft",
    "Interview language": "Gesprächssprache",
    "Interview training for apprenticeships": "Gesprächstraining für die Lehrstellensuche",
    "Interviewer": "Interviewer:in",
    "Introduction": "Vorstellung",
    "It's okay to call politely and ask about the status of your application.": "Es ist okay, höflich anzurufen und nach dem Stand deiner Bewerbung zu fragen.",
    "Job ad text": "Text des Inserats",
    "Join class": "Klasse beitreten",
    "Just for you - we'll ask again afterwards so you can see the difference.": "Nur für dich – wir fragen danach nochmals, damit du den Unterschied siehst.",
    "Keep track of every company - from trial days to the offer. Drag cards to change their stage.": "Behalte jeden Betrieb im Blick – vom Schnuppern bis zur Zusage. Zieh Karten, um ihre Phase zu ändern.",
    "Language of the app": "Sprache der App",
    "Last practice": "Zuletzt geübt",
    "Leave class": "Klasse verlassen",
    "Leave interview": "Gespräch verlassen",
    "Leave - you can continue later": "Verlassen – du kannst später weitermachen",
    "Length": "Länge",
    "Let my teacher read my interview answers": "Meine Lehrperson darf meine Antworten lesen",
    "Let's pause for a moment": "Machen wir kurz Pause",
    "Like the real interview: no tips in between. Your full feedback waits in your summit log at the end.": "Wie im echten Gespräch: keine Tipps zwischendurch. Dein ganzes Feedback wartet am Schluss in deinem Gipfelbuch.",
    "Like the real thing - feedback at the end": "Wie echt – Feedback am Schluss",
    "Made for the classroom": "Gemacht für den Unterricht",
    "Mode": "Modus",
    "Motivation": "Motivation",
    "Moved to {s}": "Verschoben nach {s}",
    "My apprenticeships": "Meine Lehrstellen",
    "My class": "Meine Klasse",
    "Name the strength": "Nenne die Stärke",
    "Nervous? Try this:": "Nervös? Versuch das:",
    "New attempt - use the coach's tip.": "Neuer Versuch – nutz den Tipp des Coachs.",
    "New code": "Neuer Code",
    "Next drill": "Nächstes Kurztraining",
    "Next time:": "Nächstes Mal:",
    "No drills due": "Keine Kurztrainings fällig",
    "No e-mail needed. Letters, digits, dot or dash.": "Keine E-Mail nötig. Buchstaben, Ziffern, Punkt oder Bindestrich.",
    "No interviews yet.": "Noch keine Gespräche.",
    "No reply from {company} for {n} days.": "Seit {n} Tagen keine Antwort von {company}.",
    "No students yet": "Noch keine Lernenden",
    "Not enough answers for a profile yet.": "Noch nicht genug Antworten für ein Profil.",
    "Not great": "Nicht so gut",
    "Notes": "Notizen",
    "Nothing due. A good day for a full practice interview.": "Nichts fällig. Ein guter Tag für ein ganzes Übungsgespräch.",
    "Now vs. your first interview": "Jetzt vs. dein erstes Gespräch",
    "Offer": "Zusage",
    "Offline demo coach": "Offline-Demo-Coach",
    "Okay": "Okay",
    "Open": "Öffnen",
    "Open my summit log": "Mein Gipfelbuch öffnen",
    "Overall score over time": "Gesamtpunktzahl im Verlauf",
    "Pair work: each student tells a 60-second story using Situation → what I did → result. Partner asks 'and what did YOU do?'.": "Partnerarbeit: Alle erzählen eine 60-Sekunden-Geschichte nach Situation → was ich gemacht habe → Ergebnis. Die Partnerin oder der Partner fragt: «Und was hast DU gemacht?»",
    "Password": "Passwort",
    "Paste a job ad to tailor the questions (optional)": "Füge ein Inserat ein, um die Fragen anzupassen (optional)",
    "Paste it here - your rehearsal will ask about it.": "Füge es hier ein – deine Hauptprobe fragt danach.",
    "Paste the text of the apprenticeship ad here…": "Füge hier den Text des Lehrstelleninserats ein…",
    "Powered by Apertus (EPFL · ETH Zurich · CSCS)": "Mit Apertus (EPFL · ETH Zurich · CSCS)",
    "Practice interview": "Übungsgespräch",
    "Practice sessions per week": "Übungseinheiten pro Woche",
    "Practice that sticks": "Üben, das hängen bleibt",
    "Practise again": "Nochmals üben",
    "Practise your apprenticeship interview as often as you like - in German, French, Italian or Swiss German. An AI interviewer asks real questions, a coach shows you what already works and what to try next.": "Übe dein Vorstellungsgespräch für die Lehrstelle so oft du willst – auf Deutsch, Französisch, Italienisch oder Schweizerdeutsch. Eine KI stellt echte Fragen, ein Coach zeigt dir, was schon klappt und was du als Nächstes versuchen kannst.",
    "Preferred interview language": "Bevorzugte Gesprächssprache",
    "Previous session": "Vorherige Einheit",
    "Print / PDF": "Drucken / PDF",
    "Profile & privacy": "Profil & Datenschutz",
    "Profile saved": "Profil gespeichert",
    "Progress": "Fortschritt",
    "Rate your answers before the feedback appears - after 3 ratings you'll see how well you judge yourself.": "Bewerte deine Antworten, bevor das Feedback erscheint – nach 3 Bewertungen siehst du, wie gut du dich selbst einschätzt.",
    "Ready for a practice round?": "Bereit für eine Übungsrunde?",
    "Rehearse exactly this interview - with questions about this company and its job ad.": "Probe genau dieses Gespräch – mit Fragen zu diesem Betrieb und seinem Inserat.",
    "Rehearse interview": "Gespräch proben",
    "Rehearse this interview": "Dieses Gespräch proben",
    "Rehearsed {n}×": "{n}× geprobt",
    "Rejected": "Absage",
    "Relevance": "Relevanz",
    "Remove": "Entfernen",
    "Removed": "Entfernt",
    "Result / what you learned": "Ergebnis / was du gelernt hast",
    "Role play greetings and closings: handshake, 'Grüezi Frau…', full sentences, thanking at the end.": "Rollenspiel Begrüssung und Verabschiedung: Händedruck, «Grüezi Frau…», ganze Sätze, Dank zum Schluss.",
    "Rule-based stand-in. Connect Apertus for real feedback.": "Regelbasierter Ersatz. Verbinde Apertus für echtes Feedback.",
    "Powered by Apertus, Switzerland's open language model. No e-mail needed. This demo is hosted on Google Cloud; schools can also run it on their own server.": "Mit Apertus, dem offenen Sprachmodell der Schweiz. Keine E-Mail nötig. Diese Demo läuft auf Google Cloud; Schulen können Zusage auf ihrem eigenen Server betreiben.",
    "Save": "Speichern",
    "Save profile": "Profil speichern",
    "Saved": "Gespeichert",
    "School": "Schule",
    "School / class": "Schule / Klasse",
    "Score profile": "Punkteprofil",
    "Scores and activity of your students. Answer texts are only visible if a student agrees.": "Punkte und Aktivität Ihrer Lernenden. Antworttexte sind nur sichtbar, wenn die Person zustimmt.",
    "Self-assessment": "Selbsteinschätzung",
    "Self-awareness": "Selbstreflexion",
    "Send (Ctrl+Enter)": "Senden (Ctrl+Enter)",
    "Send answer": "Antwort senden",
    "Sessions": "Einheiten",
    "Set up your interview": "Gespräch einrichten",
    "Share the class code {code} with your students.": "Teilen Sie den Klassencode {code} mit Ihren Lernenden.",
    "Short": "Kurz",
    "Short real moments you can use as examples: a problem you solved, a time you helped someone. The hint button reminds you of them during interviews.": "Kurze echte Momente, die du als Beispiele nutzen kannst: ein Problem, das du gelöst hast, eine Situation, in der du jemandem geholfen hast. Der Tipp-Knopf erinnert dich im Gespräch daran.",
    "Show answers": "Antworten zeigen",
    "Sign in": "Anmelden",
    "Sign out": "Abmelden",
    "Situation": "Situation",
    "Situations": "Situationen",
    "Skip and show feedback": "Überspringen und Feedback zeigen",
    "Something went wrong - try again.": "Etwas ist schiefgelaufen – versuch es nochmals.",
    "Spaced practice · drill boxes": "Verteiltes Üben · Trainingsboxen",
    "Start interview": "Gespräch starten",
    "Start practice interview": "Übungsgespräch starten",
    "Start practising": "Jetzt üben",
    "Status": "Status",
    "Stop for today": "Für heute aufhören",
    "Story bank": "Geschichtensammlung",
    "Strength bingo: students collect three strengths from classmates, each with a moment they observed it.": "Stärken-Bingo: Die Lernenden sammeln bei Mitschülerinnen und Mitschülern drei Stärken, jeweils mit einem Moment, in dem sie sie beobachtet haben.",
    "Strengths": "Stärken",
    "Strong": "Stark",
    "Strong:": "Stark:",
    "Student": "Lernende:r",
    "Students join with a 6-letter code - no e-mail addresses needed.": "Lernende treten mit einem 6-stelligen Code bei – keine E-Mail-Adressen nötig.",
    "Students × criteria (last 3 interviews)": "Lernende × Kriterien (letzte 3 Gespräche)",
    "Summit log": "Gipfelbuch",
    "Summit points per interview": "Gipfelpunkte pro Gespräch",
    "Swiss and private": "Schweizerisch und privat",
    "Teachers see who practised and where the class struggles - transcripts only if a student agrees. Fits the career-choice lessons of Lehrplan 21.": "Lehrpersonen sehen, wer geübt hat und wo die Klasse Mühe hat – Transkripte nur mit Zustimmung der Lernenden. Passt zur Berufswahl im Lehrplan 21.",
    "The coach did not answer - try again.": "Der Coach hat nicht geantwortet – versuch es nochmals.",
    "The next interviews will train these on purpose:": "Die nächsten Gespräche trainieren gezielt:",
    "This permanently deletes your account, interviews, drills and apprenticeships. It cannot be undone.": "Damit werden dein Konto, deine Gespräche, Kurztrainings und Lehrstellen endgültig gelöscht. Das kann nicht rückgängig gemacht werden.",
    "This session": "Diese Einheit",
    "Today": "Heute",
    "Tough round? That's normal. The next one usually feels easier.": "Harte Runde? Das ist normal. Die nächste fühlt sich meist leichter an.",
    "Town": "Ort",
    "Training": "Training",
    "Trial apprenticeship": "Schnupperlehre",
    "Trial apprenticeships & experience": "Schnupperlehren & Erfahrung",
    "Trial-day debrief: each student writes 3 sentences 'What surprised me in my Schnupperlehre and why I want this job'.": "Schnupper-Rückblick: Alle schreiben 3 Sätze «Was mich in meiner Schnupperlehre überrascht hat und warum ich diesen Beruf will».",
    "Try as student": "Als Schüler:in testen",
    "Try as teacher": "Als Lehrperson testen",
    "Try next": "Als Nächstes",
    "Try the coach": "Coach ausprobieren",
    "Try this answer again": "Diese Antwort nochmals versuchen",
    "Turn on the interviewer's voice": "Stimme der Interviewerin einschalten",
    "Undo": "Rückgängig",
    "Username": "Benutzername",
    "Vocational trainer · Pflegezentrum Calanda, Chur": "Berufsbildnerin · Pflegezentrum Calanda, Chur",
    "Voice on - the interviewer speaks": "Stimme an – die Interviewerin spricht",
    "Waiting for an answer": "Warten auf Antwort",
    "Welcome!": "Willkommen!",
    "What YOU did": "Was DU gemacht hast",
    "What already works": "Was schon gut klappt",
    "What connects you to this job?": "Was verbindet dich mit diesem Beruf?",
    "What do you enjoy doing?": "Was machst du gern?",
    "What does a typical day look like?": "Wie sieht ein typischer Tag aus?",
    "What worked": "Was gut lief",
    "When will you decide?": "Wann entscheiden Sie sich?",
    "Where did you do a Schnupperlehre? What did you do there?": "Wo hast du geschnuppert? Was hast du dort gemacht?",
    "Where the class struggles - and a lesson idea": "Wo die Klasse Mühe hat – und eine Unterrichtsidee",
    "Who are you?": "Wer bist du?",
    "Why this company": "Warum dieser Betrieb",
    "You are in": "Du bist in",
    "You feel more confident than before. That's what practice does.": "Du fühlst dich sicherer als vorher. Das macht Üben aus.",
    "You joined {name}": "Du bist {name} beigetreten",
    "You judge yourself realistically - a real skill for interviews.": "Du schätzt dich realistisch ein – eine echte Stärke für Gespräche.",
    "You rated yourself a bit higher than the coach did.": "Du hast dich etwas höher eingeschätzt als der Coach.",
    "You tend to rate yourself higher than the coach. Check: did you give a concrete example?": "Du schätzt dich oft höher ein als der Coach. Prüf: Hast du ein konkretes Beispiel gegeben?",
    "You were stricter with yourself than the coach - it went better than you thought!": "Du warst strenger mit dir als der Coach – es lief besser, als du dachtest!",
    "You're stricter with yourself than the coach. You're better than you think!": "Du bist strenger mit dir als der Coach. Du bist besser, als du denkst!",
    "You've rehearsed this one {n}× - best score {s}.": "Du hast dieses Gespräch {n}× geprobt – Bestwert {s}.",
    "Your answer": "Deine Antwort",
    "Your answer…": "Deine Antwort…",
    "Your coach": "Dein Coach",
    "Your coach is writing your feedback…": "Dein Coach schreibt dein Feedback…",
    "Your confidence is stable - keep going, it grows with repetition.": "Dein Selbstvertrauen ist stabil – bleib dran, es wächst mit jeder Wiederholung.",
    "Your data": "Deine Daten",
    "Your focus": "Dein Fokus",
    "Your guess matched the coach - good self-assessment!": "Deine Schätzung passt zum Coach – gute Selbsteinschätzung!",
    "Your interview as a trail: height = score per answer": "Dein Gespräch als Wanderweg: Höhe = Punkte pro Antwort",
    "Your interviewer uses this to ask personal questions. Share only what you're comfortable with - no addresses or phone numbers needed.": "Deine Interviewerin nutzt das für persönliche Fragen. Teile nur, was für dich stimmt – Adressen oder Telefonnummern braucht es nicht.",
    "Your next stage": "Deine nächste Etappe",
    "Your path to an offer": "Dein Weg zur Zusage",
    "Your profile": "Dein Profil",
    "Your questions": "Deine Fragen",
    "Your reason": "Dein Grund",
    "Your teacher always sees scores and how often you practise. Your actual answers only if you tick this. You can change it any time.": "Deine Lehrperson sieht immer Punkte und wie oft du übst. Deine Antworten nur, wenn du das ankreuzt. Du kannst es jederzeit ändern.",
    "Your trail starts with the first interview": "Dein Weg beginnt mit dem ersten Gespräch",
    "Your weakest answers are now 2-minute drills": "Deine schwächsten Antworten sind jetzt 2-Minuten-Kurztrainings",
    "Zusage runs on Apertus, the open Swiss language model, on this server. Your answers are not used to train any model. Answer texts are deleted automatically after 180 days; scores stay for your progress.": "Zusage läuft mit Apertus, dem offenen Schweizer Sprachmodell, auf diesem Server. Deine Antworten werden nicht zum Trainieren von Modellen verwendet. Antworttexte werden nach 180 Tagen automatisch gelöscht; die Punkte bleiben für deinen Fortschritt.",
    "a real moment from your trial apprenticeship - that is convincing.": "ein echter Moment aus deiner Schnupperlehre – das überzeugt.",
    "about 15 min": "ca. 15 Min.",
    "about 6 min": "ca. 6 Min.",
    "add what YOU learned from it, e.g. patience.": "ergänze, was DU daraus gelernt hast, z. B. Geduld.",
    "after": "nachher",
    "answer": "Antwort",
    "backup coach": "Ersatz-Coach",
    "before": "vorher",
    "best": "Bestwert",
    "confidence per session": "Selbstvertrauen pro Einheit",
    "day streak": "Tage in Folge",
    "due": "fällig",
    "e.g. Sek A, 3rd year": "z. B. Sek A, 3. Klasse",
    "follow-up": "Nachfrage",
    "has an offer": "hat eine Zusage",
    "have an offer": "haben eine Zusage",
    "interview soon": "Gespräch bald",
    "interviews": "Gespräche",
    "last score": "letzte Punktzahl",
    "low confidence": "wenig Selbstvertrauen",
    "model calls": "Modellaufrufe",
    "more interviews coming up": "weitere Gespräche geplant",
    "need a nudge": "brauchen einen Anstoss",
    "no data": "keine Daten",
    "not practising": "übt nicht",
    "of 100 summit points": "von 100 Gipfelpunkten",
    "of your guesses matched the coach ({n} answers).": "deiner Schätzungen passten zum Coach ({n} Antworten).",
    "per answer": "pro Antwort",
    "practised this week": "diese Woche geübt",
    "questions": "Fragen",
    "second attempt": "zweiter Versuch",
    "shares answers with you": "teilt Antworten mit Ihnen",
    "students": "Lernende",
    "very confident": "sehr sicher",
    "very nervous": "sehr nervös",
    "vs. last time": "vs. letztes Mal",
    "with job ad": "mit Inserat",
    "{name} is listening…": "{name} hört zu…",
    "{n} short drills are waiting - about {m} minutes.": "{n} kurze Kurztrainings warten – etwa {m} Minuten.",
  },
  fr: {
    "Welcome to Zusage, {name}!": "Bienvenue sur Zusage, {name} !",
    "Three quick questions so your interviewer can ask about YOU. No addresses or phone numbers needed.": "Trois questions rapides pour que ton interlocuteur puisse parler de TOI. Pas besoin d'adresse ni de numéro de téléphone.",
    "Separate with commas": "Séparer par des virgules",
    "One moment you're proud of": "Un moment dont tu es fier·ère",
    "A problem you solved or a time you helped someone - great material for answers.": "Un problème que tu as résolu ou une fois où tu as aidé quelqu'un – parfait pour tes réponses.",
    "Skip for now": "Passer pour l'instant",
    "Next": "Suivant",
    "Let's go": "C'est parti",
    "2 years · Federal VET Certificate": "2 ans · attestation fédérale",
    "3–4 years · Federal VET Diploma": "3–4 ans · certificat fédéral de capacité",
    "(deleted after the retention period)": "(supprimées après la durée de conservation)",
    "10 questions · about 15 min": "10 questions · env. 15 min",
    "2 min": "2 min",
    "5 questions · about 6 min": "5 questions · env. 6 min",
    "A drill moves up a box when you answer it well, and back to box 1 when not.": "Un entraînement express avance d'une boîte si tu réponds bien, sinon il retourne dans la boîte 1.",
    "A real experience (e.g. trial apprenticeship)": "Une vraie expérience (p. ex. stage d'orientation)",
    "A structure that works:": "Une structure qui marche :",
    "About you": "À propos de toi",
    "Add a hobby + Enter": "Ajoute un hobby + Entrée",
    "Add a story": "Ajouter une histoire",
    "Add an apprenticeship": "Ajouter une place d'apprentissage",
    "Add apprenticeship": "Ajouter une place",
    "After each interview, your weakest answers come back here after 1, 3 and 7 days.": "Après chaque entretien, tes réponses les plus faibles reviennent ici après 1, 3 et 7 jours.",
    "Age": "Âge",
    "All interviews": "Tous les entretiens",
    "Answer by answer": "Réponse par réponse",
    "Answer in dialect or standard German…": "Réponds en dialecte ou en allemand standard…",
    "Answer, see what worked, try again right away. Weak answers come back as 2-minute drills on day 1, 3 and 7 - spaced practice, like learning vocabulary.": "Réponds, vois ce qui a marché, réessaie tout de suite. Les réponses faibles reviennent en entraînements express de 2 minutes aux jours 1, 3 et 7 – une pratique espacée, comme pour apprendre du vocabulaire.",
    "Answers private - you see scores and goals only.": "Réponses privées – vous voyez seulement les scores et les objectifs.",
    "Applications": "Candidatures",
    "Applications in the class": "Candidatures dans la classe",
    "Applied": "Postulé",
    "Apprenticeship": "Apprentissage",
    "Apprenticeship added": "Place d'apprentissage ajoutée",
    "At least 8 characters.": "Au moins 8 caractères.",
    "Back to class": "Retour à la classe",
    "Back to today": "Retour à aujourd'hui",
    "Based on your words:": "D'après tes mots :",
    "Best moment:": "Meilleur moment :",
    "Beta · type in dialect": "Bêta · écris en dialecte",
    "Box {n}": "Boîte {n}",
    "Breathe in for 4 seconds, out for 6. Then answer the first sentence slowly.": "Inspire 4 secondes, expire 6. Puis réponds lentement à la première phrase.",
    "Built for Hack Apertus 2026 · FHGR challenge · Apache-2.0": "Développé pour Hack Apertus 2026 · challenge FHGR · Apache-2.0",
    "Can I do the vocational baccalaureate (BM)?": "Est-ce que je peux faire la maturité professionnelle (MP) ?",
    "Can't reach the Zusage server": "Impossible de joindre le serveur Zusage",
    "Cancel": "Annuler",
    "Check in with:": "À contacter :",
    "Choose an apprenticeship first.": "Choisis d'abord une place d'apprentissage.",
    "Choose what feels right today. You can always pause, retry an answer or stop early.": "Choisis ce qui te convient aujourd'hui. Tu peux toujours faire une pause, refaire une réponse ou t'arrêter plus tôt.",
    "Clarity": "Clarté",
    "Class": "Classe",
    "Class code": "Code de classe",
    "Class code (optional)": "Code de classe (facultatif)",
    "Class code not found": "Code de classe introuvable",
    "Class name": "Nom de la classe",
    "Class profile": "Profil de la classe",
    "Coach feedback": "Feedback du coach",
    "Coach model": "Modèle du coach",
    "Coach tips after every answer, retry allowed": "Conseils du coach après chaque réponse, nouvel essai possible",
    "Coach: Apertus": "Coach : Apertus",
    "Code copied": "Code copié",
    "Communication": "Communication",
    "Company": "Entreprise",
    "Company research sprint: 10 minutes on the company website, note 2 facts to mention in the interview.": "Sprint de recherche sur l'entreprise : 10 minutes sur son site web, noter 2 faits à mentionner pendant l'entretien.",
    "Complete": "Complet",
    "Concrete examples": "Exemples concrets",
    "Confidence before → after": "Confiance avant → après",
    "Confidence {n} of 5": "Confiance {n} sur 5",
    "Congratulations on your offer! 🎉": "Félicitations pour ta place ! 🎉",
    "Contact person": "Personne de contact",
    "Continue": "Continuer",
    "Continue practising": "Continuer à t'entraîner",
    "Copy": "Copier",
    "Could not move the card - try again.": "Impossible de déplacer la carte – réessaie.",
    "Could not save - check the fields.": "Échec de l'enregistrement – vérifie les champs.",
    "Could not start the interview.": "Impossible de démarrer l'entretien.",
    "Create account": "Créer un compte",
    "Create class": "Créer la classe",
    "Create your first class": "Créez votre première classe",
    "Criteria (last 3 interviews)": "Critères (3 derniers entretiens)",
    "Delete my account": "Supprimer mon compte",
    "Delete permanently": "Supprimer définitivement",
    "Delete your account?": "Supprimer ton compte ?",
    "Demo accounts with a fictional class - no sign-up needed.": "Comptes de démo avec une classe fictive – sans inscription.",
    "Dictate (uses your browser's speech recognition)": "Dicter (utilise la reconnaissance vocale de ton navigateur)",
    "Difficulty {n} of 3": "Difficulté {n} sur 3",
    "Download my data": "Télécharger mes données",
    "Dream apprenticeship": "Apprentissage de rêve",
    "Dress rehearsal": "Répétition générale",
    "Drill": "Entraînement express",
    "Due today · spaced practice": "À faire aujourd'hui · pratique espacée",
    "Every comment quotes your own words, scored on six criteria from Swiss vocational education. No grades, no shaming - one concrete next step.": "Chaque commentaire cite tes propres mots, évalués selon six critères de la formation professionnelle suisse. Pas de notes, pas d'humiliation – une prochaine étape concrète.",
    "Every practice interview, drill and retry - measured on the same six criteria.": "Chaque entretien d'entraînement, entraînement express et nouvel essai – mesuré selon les mêmes six critères.",
    "Example of a practice interview": "Exemple d'entretien d'entraînement",
    "Feedback you can trust": "Un feedback fiable",
    "Finish": "Terminer",
    "Finish a practice interview to see your profile here.": "Termine un entretien d'entraînement pour voir ton profil ici.",
    "Finish the interview?": "Terminer l'entretien ?",
    "First attempt:": "Premier essai :",
    "First name or nickname": "Prénom ou surnom",
    "Five questions, about six minutes. Your coach shows you what already works.": "Cinq questions, environ six minutes. Ton coach te montre ce qui marche déjà.",
    "Focus": "Focus",
    "For a real application? (optional)": "Pour une vraie candidature ? (facultatif)",
    "From your story bank": "De ta banque d'histoires",
    "From your teacher. You can add it later.": "De ton enseignant·e. Tu peux l'ajouter plus tard.",
    "General practice": "Entraînement général",
    "Give an example": "Donne un exemple",
    "Good questions to ask:": "Bonnes questions à poser :",
    "Goodbye": "Au revoir",
    "Guess first - then compare with your coach. This trains your inner judge.": "Devine d'abord – puis compare avec ton coach. Ça entraîne ton jugement intérieur.",
    "Headline first: answer any question in one sentence, then add one reason. Practise with a timer (30 s).": "La phrase clé d'abord : répondre à chaque question en une phrase, puis ajouter une raison. S'entraîner avec un minuteur (30 s).",
    "Hello {name}!": "Salut {name} !",
    "Hide": "Masquer",
    "Hide answers": "Masquer les réponses",
    "Hide example": "Masquer l'exemple",
    "Hide hint": "Masquer l'indice",
    "Hint": "Indice",
    "Hobbies": "Loisirs",
    "How confident do you feel about job interviews now?": "À quel point te sens-tu à l'aise en entretien maintenant ?",
    "How confident do you feel about job interviews right now?": "À quel point te sens-tu à l'aise en entretien en ce moment ?",
    "How did that answer go?": "Comment s'est passée cette réponse ?",
    "How far you've come": "Le chemin parcouru",
    "How it could sound": "Ça pourrait donner ça",
    "How it helps in the job": "En quoi ça aide dans le métier",
    "I'm a student": "Je suis élève",
    "I'm a teacher": "Je suis enseignant·e",
    "I'm stuck - give me a hint": "Je bloque – donne-moi un indice",
    "In {n} days": "Dans {n} jours",
    "Interested": "Intéressé·e",
    "Interview": "Entretien",
    "Interview at {company}": "Entretien chez {company}",
    "Interview coach for your apprenticeship": "Coach d'entretien pour ton apprentissage",
    "Interview completed": "Entretien terminé",
    "Interview date": "Date de l'entretien",
    "Interview finished!": "Entretien terminé !",
    "Interview in progress": "Entretien en cours",
    "Interview language": "Langue de l'entretien",
    "Interview training for apprenticeships": "Entraînement aux entretiens d'apprentissage",
    "Interviewer": "Recruteur·euse",
    "Introduction": "Présentation",
    "It's okay to call politely and ask about the status of your application.": "Tu peux tout à fait appeler poliment pour demander où en est ta candidature.",
    "Job ad text": "Texte de l'annonce",
    "Join class": "Rejoindre la classe",
    "Just for you - we'll ask again afterwards so you can see the difference.": "Juste pour toi – on te redemande après pour que tu voies la différence.",
    "Keep track of every company - from trial days to the offer. Drag cards to change their stage.": "Garde un œil sur chaque entreprise – du stage jusqu'à l'acceptation. Glisse les cartes pour changer leur étape.",
    "Language of the app": "Langue de l'app",
    "Last practice": "Dernier entraînement",
    "Leave class": "Quitter la classe",
    "Leave interview": "Quitter l'entretien",
    "Leave - you can continue later": "Quitter – tu pourras continuer plus tard",
    "Length": "Durée",
    "Let my teacher read my interview answers": "Mon enseignant·e peut lire mes réponses",
    "Let's pause for a moment": "Faisons une petite pause",
    "Like the real interview: no tips in between. Your full feedback waits in your summit log at the end.": "Comme en vrai : pas de conseils en cours de route. Tout ton feedback t'attend à la fin dans ton carnet de sommet.",
    "Like the real thing - feedback at the end": "Comme en vrai – feedback à la fin",
    "Made for the classroom": "Conçu pour la classe",
    "Mode": "Mode",
    "Motivation": "Motivation",
    "Moved to {s}": "Déplacée vers {s}",
    "My apprenticeships": "Mes apprentissages",
    "My class": "Ma classe",
    "Name the strength": "Nomme la force",
    "Nervous? Try this:": "Stressé·e ? Essaie ça :",
    "New attempt - use the coach's tip.": "Nouvel essai – utilise le conseil du coach.",
    "New code": "Nouveau code",
    "Next drill": "Entraînement suivant",
    "Next time:": "La prochaine fois :",
    "No drills due": "Aucun entraînement express à faire",
    "No e-mail needed. Letters, digits, dot or dash.": "Pas besoin d'e-mail. Lettres, chiffres, point ou tiret.",
    "No interviews yet.": "Pas encore d'entretiens.",
    "No reply from {company} for {n} days.": "Pas de réponse de {company} depuis {n} jours.",
    "No students yet": "Pas encore d'élèves",
    "Not enough answers for a profile yet.": "Pas encore assez de réponses pour un profil.",
    "Not great": "Pas terrible",
    "Notes": "Notes",
    "Nothing due. A good day for a full practice interview.": "Rien à faire. Un bon jour pour un entretien d'entraînement complet.",
    "Now vs. your first interview": "Maintenant vs ton premier entretien",
    "Offer": "Acceptation",
    "Offline demo coach": "Coach démo hors ligne",
    "Okay": "Correct",
    "Open": "Ouvrir",
    "Open my summit log": "Ouvrir mon carnet de sommet",
    "Overall score over time": "Score global dans le temps",
    "Pair work: each student tells a 60-second story using Situation → what I did → result. Partner asks 'and what did YOU do?'.": "Travail en duo : chaque élève raconte une histoire de 60 secondes selon Situation → ce que j'ai fait → résultat. Le ou la partenaire demande « Et toi, qu'est-ce que TU as fait ? ».",
    "Password": "Mot de passe",
    "Paste a job ad to tailor the questions (optional)": "Colle une annonce pour adapter les questions (facultatif)",
    "Paste it here - your rehearsal will ask about it.": "Colle-la ici – ta répétition générale posera des questions dessus.",
    "Paste the text of the apprenticeship ad here…": "Colle ici le texte de l'annonce d'apprentissage…",
    "Powered by Apertus (EPFL · ETH Zurich · CSCS)": "Propulsé par Apertus (EPFL · ETH Zurich · CSCS)",
    "Practice interview": "Entretien d'entraînement",
    "Practice sessions per week": "Séances par semaine",
    "Practice that sticks": "Une pratique qui reste",
    "Practise again": "Réessayer",
    "Practise your apprenticeship interview as often as you like - in German, French, Italian or Swiss German. An AI interviewer asks real questions, a coach shows you what already works and what to try next.": "Entraîne-toi à l'entretien d'apprentissage aussi souvent que tu veux – en allemand, français, italien ou suisse allemand. Une IA te pose de vraies questions, un coach te montre ce qui marche déjà et quoi essayer ensuite.",
    "Preferred interview language": "Langue d'entretien préférée",
    "Previous session": "Séance précédente",
    "Print / PDF": "Imprimer / PDF",
    "Profile & privacy": "Profil & confidentialité",
    "Profile saved": "Profil enregistré",
    "Progress": "Progrès",
    "Rate your answers before the feedback appears - after 3 ratings you'll see how well you judge yourself.": "Évalue tes réponses avant le feedback – après 3 évaluations, tu verras à quel point tu te juges bien.",
    "Ready for a practice round?": "Prêt·e pour un tour d'entraînement ?",
    "Rehearse exactly this interview - with questions about this company and its job ad.": "Répète exactement cet entretien – avec des questions sur cette entreprise et son annonce.",
    "Rehearse interview": "Répéter l'entretien",
    "Rehearse this interview": "Répéter cet entretien",
    "Rehearsed {n}×": "Répété {n}×",
    "Rejected": "Refus",
    "Relevance": "Pertinence",
    "Remove": "Retirer",
    "Removed": "Retiré",
    "Result / what you learned": "Résultat / ce que tu as appris",
    "Role play greetings and closings: handshake, 'Grüezi Frau…', full sentences, thanking at the end.": "Jeu de rôle accueil et au revoir : poignée de main, « Bonjour Madame… », phrases complètes, remercier à la fin.",
    "Rule-based stand-in. Connect Apertus for real feedback.": "Remplaçant basé sur des règles. Connecte Apertus pour un vrai feedback.",
    "Powered by Apertus, Switzerland's open language model. No e-mail needed. This demo is hosted on Google Cloud; schools can also run it on their own server.": "Propulsé par Apertus, le modèle de langue ouvert suisse. Pas besoin d'e-mail. Cette démo utilise Google Cloud ; les écoles peuvent aussi l'héberger sur leur serveur.",
    "Save": "Enregistrer",
    "Save profile": "Enregistrer le profil",
    "Saved": "Enregistré",
    "School": "École",
    "School / class": "École / classe",
    "Score profile": "Profil des scores",
    "Scores and activity of your students. Answer texts are only visible if a student agrees.": "Scores et activité de vos élèves. Les réponses ne sont visibles que si l'élève est d'accord.",
    "Self-assessment": "Auto-évaluation",
    "Self-awareness": "Connaissance de soi",
    "Send (Ctrl+Enter)": "Envoyer (Ctrl+Entrée)",
    "Send answer": "Envoyer la réponse",
    "Sessions": "Séances",
    "Set up your interview": "Prépare ton entretien",
    "Share the class code {code} with your students.": "Partagez le code de classe {code} avec vos élèves.",
    "Short": "Court",
    "Short real moments you can use as examples: a problem you solved, a time you helped someone. The hint button reminds you of them during interviews.": "De courts moments réels à utiliser comme exemples : un problème que tu as résolu, une fois où tu as aidé quelqu'un. Le bouton indice te les rappelle pendant l'entretien.",
    "Show answers": "Afficher les réponses",
    "Sign in": "Se connecter",
    "Sign out": "Se déconnecter",
    "Situation": "Situation",
    "Situations": "Situations",
    "Skip and show feedback": "Passer et voir le feedback",
    "Something went wrong - try again.": "Un problème est survenu – réessaie.",
    "Spaced practice · drill boxes": "Pratique espacée · boîtes d'entraînement",
    "Start interview": "Commencer l'entretien",
    "Start practice interview": "Commencer un entretien d'entraînement",
    "Start practising": "Commencer",
    "Status": "Statut",
    "Stop for today": "Arrêter pour aujourd'hui",
    "Story bank": "Banque d'histoires",
    "Strength bingo: students collect three strengths from classmates, each with a moment they observed it.": "Bingo des forces : les élèves récoltent trois forces auprès de leurs camarades, chacune avec un moment où elle a été observée.",
    "Strengths": "Points forts",
    "Strong": "Fort",
    "Strong:": "Fort :",
    "Student": "Élève",
    "Students join with a 6-letter code - no e-mail addresses needed.": "Les élèves rejoignent la classe avec un code à 6 lettres – sans adresse e-mail.",
    "Students × criteria (last 3 interviews)": "Élèves × critères (3 derniers entretiens)",
    "Summit log": "Carnet de sommet",
    "Summit points per interview": "Points sommet par entretien",
    "Swiss and private": "Suisse et privé",
    "Teachers see who practised and where the class struggles - transcripts only if a student agrees. Fits the career-choice lessons of Lehrplan 21.": "Les enseignant·e·s voient qui s'est entraîné et où la classe a des difficultés – les transcriptions seulement avec l'accord de l'élève. S'intègre aux cours de choix professionnel (Lehrplan 21 / PER).",
    "The coach did not answer - try again.": "Le coach n'a pas répondu – réessaie.",
    "The next interviews will train these on purpose:": "Les prochains entretiens entraîneront exprès :",
    "This permanently deletes your account, interviews, drills and apprenticeships. It cannot be undone.": "Cela supprime définitivement ton compte, tes entretiens, entraînements et apprentissages. C'est irréversible.",
    "This session": "Cette séance",
    "Today": "Aujourd'hui",
    "Tough round? That's normal. The next one usually feels easier.": "Tour difficile ? C'est normal. Le prochain paraît souvent plus facile.",
    "Town": "Localité",
    "Training": "Entraînement",
    "Trial apprenticeship": "Stage d'orientation",
    "Trial apprenticeships & experience": "Stages & expérience",
    "Trial-day debrief: each student writes 3 sentences 'What surprised me in my Schnupperlehre and why I want this job'.": "Retour sur le stage : chaque élève écrit 3 phrases « Ce qui m'a surpris pendant mon stage et pourquoi je veux ce métier ».",
    "Try as student": "Essayer comme élève",
    "Try as teacher": "Essayer comme enseignant·e",
    "Try next": "À essayer",
    "Try the coach": "Essayer le coach",
    "Try this answer again": "Réessayer cette réponse",
    "Turn on the interviewer's voice": "Activer la voix du recruteur",
    "Undo": "Annuler",
    "Username": "Nom d'utilisateur",
    "Vocational trainer · Pflegezentrum Calanda, Chur": "Formatrice · Pflegezentrum Calanda, Coire",
    "Voice on - the interviewer speaks": "Voix activée – le recruteur parle",
    "Waiting for an answer": "En attente de réponse",
    "Welcome!": "Bienvenue !",
    "What YOU did": "Ce que TU as fait",
    "What already works": "Ce qui marche déjà",
    "What connects you to this job?": "Qu'est-ce qui te lie à ce métier ?",
    "What do you enjoy doing?": "Qu'est-ce que tu aimes faire ?",
    "What does a typical day look like?": "À quoi ressemble une journée type ?",
    "What worked": "Ce qui a marché",
    "When will you decide?": "Quand allez-vous décider ?",
    "Where did you do a Schnupperlehre? What did you do there?": "Où as-tu fait un stage ? Qu'est-ce que tu y as fait ?",
    "Where the class struggles - and a lesson idea": "Où la classe a des difficultés – et une idée de leçon",
    "Who are you?": "Qui es-tu ?",
    "Why this company": "Pourquoi cette entreprise",
    "You are in": "Tu es dans",
    "You feel more confident than before. That's what practice does.": "Tu te sens plus sûr·e qu'avant. C'est l'effet de l'entraînement.",
    "You joined {name}": "Tu as rejoint {name}",
    "You judge yourself realistically - a real skill for interviews.": "Tu te juges de façon réaliste – un vrai atout en entretien.",
    "You rated yourself a bit higher than the coach did.": "Tu t'es noté·e un peu plus haut que le coach.",
    "You tend to rate yourself higher than the coach. Check: did you give a concrete example?": "Tu te notes souvent plus haut que le coach. Vérifie : as-tu donné un exemple concret ?",
    "You were stricter with yourself than the coach - it went better than you thought!": "Tu as été plus sévère avec toi que le coach – ça s'est mieux passé que tu ne le pensais !",
    "You're stricter with yourself than the coach. You're better than you think!": "Tu es plus sévère avec toi que le coach. Tu es meilleur·e que tu ne le penses !",
    "You've rehearsed this one {n}× - best score {s}.": "Tu as répété cet entretien {n}× – meilleur score {s}.",
    "Your answer": "Ta réponse",
    "Your answer…": "Ta réponse…",
    "Your coach": "Ton coach",
    "Your coach is writing your feedback…": "Ton coach rédige ton feedback…",
    "Your confidence is stable - keep going, it grows with repetition.": "Ta confiance est stable – continue, elle grandit avec la répétition.",
    "Your data": "Tes données",
    "Your focus": "Ton focus",
    "Your guess matched the coach - good self-assessment!": "Ton estimation correspond à celle du coach – bonne auto-évaluation !",
    "Your interview as a trail: height = score per answer": "Ton entretien comme sentier : altitude = score par réponse",
    "Your interviewer uses this to ask personal questions. Share only what you're comfortable with - no addresses or phone numbers needed.": "Ton recruteur s'en sert pour poser des questions personnelles. Partage seulement ce qui te convient – pas besoin d'adresse ni de numéro de téléphone.",
    "Your next stage": "Ta prochaine étape",
    "Your path to an offer": "Ton chemin vers une place",
    "Your profile": "Ton profil",
    "Your questions": "Tes questions",
    "Your reason": "Ta raison",
    "Your teacher always sees scores and how often you practise. Your actual answers only if you tick this. You can change it any time.": "Ton enseignant·e voit toujours les scores et la fréquence de tes entraînements. Tes réponses seulement si tu coches ceci. Tu peux changer ça à tout moment.",
    "Your trail starts with the first interview": "Ton sentier commence avec le premier entretien",
    "Your weakest answers are now 2-minute drills": "Tes réponses les plus faibles sont maintenant des entraînements express de 2 minutes",
    "Zusage runs on Apertus, the open Swiss language model, on this server. Your answers are not used to train any model. Answer texts are deleted automatically after 180 days; scores stay for your progress.": "Zusage fonctionne avec Apertus, le modèle de langue ouvert suisse, sur ce serveur. Tes réponses ne servent à entraîner aucun modèle. Les textes des réponses sont supprimés automatiquement après 180 jours ; les scores restent pour suivre tes progrès.",
    "a real moment from your trial apprenticeship - that is convincing.": "un vrai moment de ton stage – c'est convaincant.",
    "about 15 min": "env. 15 min",
    "about 6 min": "env. 6 min",
    "add what YOU learned from it, e.g. patience.": "ajoute ce que TU en as appris, p. ex. la patience.",
    "after": "après",
    "answer": "réponse",
    "backup coach": "coach de secours",
    "before": "avant",
    "best": "meilleur",
    "confidence per session": "confiance par séance",
    "day streak": "jours d'affilée",
    "due": "à faire",
    "e.g. Sek A, 3rd year": "p. ex. 11e Harmos, voie générale",
    "follow-up": "question de relance",
    "has an offer": "a une place",
    "have an offer": "ont une place",
    "interview soon": "entretien bientôt",
    "interviews": "entretiens",
    "last score": "dernier score",
    "low confidence": "peu de confiance",
    "model calls": "appels au modèle",
    "more interviews coming up": "autres entretiens à venir",
    "need a nudge": "ont besoin d'un coup de pouce",
    "no data": "pas de données",
    "not practising": "ne s'entraîne pas",
    "of 100 summit points": "sur 100 points sommet",
    "of your guesses matched the coach ({n} answers).": "de tes estimations correspondaient au coach ({n} réponses).",
    "per answer": "par réponse",
    "practised this week": "entraîné·e·s cette semaine",
    "questions": "questions",
    "second attempt": "deuxième essai",
    "shares answers with you": "partage ses réponses avec vous",
    "students": "élèves",
    "very confident": "très à l'aise",
    "very nervous": "très stressé·e",
    "vs. last time": "vs la dernière fois",
    "with job ad": "avec annonce",
    "{name} is listening…": "{name} écoute…",
    "{n} short drills are waiting - about {m} minutes.": "{n} entraînements express t'attendent – environ {m} minutes.",
  },
  it: {
    "Welcome to Zusage, {name}!": "Benvenuto/a su Zusage, {name}!",
    "Three quick questions so your interviewer can ask about YOU. No addresses or phone numbers needed.": "Tre domande veloci, così chi ti intervista può chiederti di TE. Non servono indirizzi né numeri di telefono.",
    "Separate with commas": "Separa con virgole",
    "One moment you're proud of": "Un momento di cui sei fiero/a",
    "A problem you solved or a time you helped someone - great material for answers.": "Un problema che hai risolto o una volta in cui hai aiutato qualcuno: ottimo materiale per le risposte.",
    "Skip for now": "Salta per ora",
    "Next": "Avanti",
    "Let's go": "Si parte",
    "2 years · Federal VET Certificate": "2 anni · certificato federale",
    "3–4 years · Federal VET Diploma": "3–4 anni · attestato federale di capacità",
    "(deleted after the retention period)": "(eliminate dopo il periodo di conservazione)",
    "10 questions · about 15 min": "10 domande · circa 15 min",
    "2 min": "2 min",
    "5 questions · about 6 min": "5 domande · circa 6 min",
    "A drill moves up a box when you answer it well, and back to box 1 when not.": "Un allenamento lampo avanza di una scatola se rispondi bene, altrimenti torna alla scatola 1.",
    "A real experience (e.g. trial apprenticeship)": "Un'esperienza vera (p. es. stage di orientamento)",
    "A structure that works:": "Una struttura che funziona:",
    "About you": "Su di te",
    "Add a hobby + Enter": "Aggiungi un hobby + Invio",
    "Add a story": "Aggiungi una storia",
    "Add an apprenticeship": "Aggiungi un posto di tirocinio",
    "Add apprenticeship": "Aggiungi posto",
    "After each interview, your weakest answers come back here after 1, 3 and 7 days.": "Dopo ogni colloquio, le tue risposte più deboli tornano qui dopo 1, 3 e 7 giorni.",
    "Age": "Età",
    "All interviews": "Tutti i colloqui",
    "Answer by answer": "Risposta per risposta",
    "Answer in dialect or standard German…": "Rispondi in dialetto o in tedesco standard…",
    "Answer, see what worked, try again right away. Weak answers come back as 2-minute drills on day 1, 3 and 7 - spaced practice, like learning vocabulary.": "Rispondi, guarda cosa ha funzionato, riprova subito. Le risposte deboli tornano come allenamenti lampo di 2 minuti al giorno 1, 3 e 7 – pratica distribuita, come per imparare i vocaboli.",
    "Answers private - you see scores and goals only.": "Risposte private – vede solo i punteggi e gli obiettivi.",
    "Applications": "Candidature",
    "Applications in the class": "Candidature nella classe",
    "Applied": "Candidatura inviata",
    "Apprenticeship": "Tirocinio",
    "Apprenticeship added": "Posto di tirocinio aggiunto",
    "At least 8 characters.": "Almeno 8 caratteri.",
    "Back to class": "Torna alla classe",
    "Back to today": "Torna a oggi",
    "Based on your words:": "Dalle tue parole:",
    "Best moment:": "Momento migliore:",
    "Beta · type in dialect": "Beta · scrivi in dialetto",
    "Box {n}": "Scatola {n}",
    "Breathe in for 4 seconds, out for 6. Then answer the first sentence slowly.": "Inspira per 4 secondi, espira per 6. Poi pronuncia lentamente la prima frase.",
    "Built for Hack Apertus 2026 · FHGR challenge · Apache-2.0": "Sviluppato per Hack Apertus 2026 · challenge FHGR · Apache-2.0",
    "Can I do the vocational baccalaureate (BM)?": "Posso fare la maturità professionale (MP)?",
    "Can't reach the Zusage server": "Server di Zusage non raggiungibile",
    "Cancel": "Annulla",
    "Check in with:": "Da contattare:",
    "Choose an apprenticeship first.": "Scegli prima un posto di tirocinio.",
    "Choose what feels right today. You can always pause, retry an answer or stop early.": "Scegli ciò che ti va oggi. Puoi sempre fare una pausa, ripetere una risposta o fermarti prima.",
    "Clarity": "Chiarezza",
    "Class": "Classe",
    "Class code": "Codice della classe",
    "Class code (optional)": "Codice della classe (facoltativo)",
    "Class code not found": "Codice della classe non trovato",
    "Class name": "Nome della classe",
    "Class profile": "Profilo della classe",
    "Coach feedback": "Feedback del coach",
    "Coach model": "Modello del coach",
    "Coach tips after every answer, retry allowed": "Consigli del coach dopo ogni risposta, puoi riprovare",
    "Coach: Apertus": "Coach: Apertus",
    "Code copied": "Codice copiato",
    "Communication": "Comunicazione",
    "Company": "Azienda",
    "Company research sprint: 10 minutes on the company website, note 2 facts to mention in the interview.": "Sprint di ricerca sull'azienda: 10 minuti sul sito web, annotare 2 fatti da citare nel colloquio.",
    "Complete": "Completo",
    "Concrete examples": "Esempi concreti",
    "Confidence before → after": "Fiducia prima → dopo",
    "Confidence {n} of 5": "Fiducia {n} su 5",
    "Congratulations on your offer! 🎉": "Congratulazioni per il posto! 🎉",
    "Contact person": "Persona di contatto",
    "Continue": "Continua",
    "Continue practising": "Continua ad allenarti",
    "Copy": "Copia",
    "Could not move the card - try again.": "Impossibile spostare la scheda – riprova.",
    "Could not save - check the fields.": "Salvataggio non riuscito – controlla i campi.",
    "Could not start the interview.": "Impossibile avviare il colloquio.",
    "Create account": "Crea account",
    "Create class": "Crea classe",
    "Create your first class": "Crei la sua prima classe",
    "Criteria (last 3 interviews)": "Criteri (ultimi 3 colloqui)",
    "Delete my account": "Elimina il mio account",
    "Delete permanently": "Elimina definitivamente",
    "Delete your account?": "Eliminare il tuo account?",
    "Demo accounts with a fictional class - no sign-up needed.": "Account demo con una classe fittizia – senza registrazione.",
    "Dictate (uses your browser's speech recognition)": "Detta (usa il riconoscimento vocale del tuo browser)",
    "Difficulty {n} of 3": "Difficoltà {n} su 3",
    "Download my data": "Scarica i miei dati",
    "Dream apprenticeship": "Tirocinio dei sogni",
    "Dress rehearsal": "Prova generale",
    "Drill": "Allenamento lampo",
    "Due today · spaced practice": "Da fare oggi · pratica distribuita",
    "Every comment quotes your own words, scored on six criteria from Swiss vocational education. No grades, no shaming - one concrete next step.": "Ogni commento cita le tue parole, valutate secondo sei criteri della formazione professionale svizzera. Niente voti, niente umiliazioni – un passo concreto successivo.",
    "Every practice interview, drill and retry - measured on the same six criteria.": "Ogni colloquio di prova, allenamento lampo e nuovo tentativo – misurato sugli stessi sei criteri.",
    "Example of a practice interview": "Esempio di colloquio di prova",
    "Feedback you can trust": "Feedback di cui fidarti",
    "Finish": "Termina",
    "Finish a practice interview to see your profile here.": "Completa un colloquio di prova per vedere qui il tuo profilo.",
    "Finish the interview?": "Terminare il colloquio?",
    "First attempt:": "Primo tentativo:",
    "First name or nickname": "Nome o soprannome",
    "Five questions, about six minutes. Your coach shows you what already works.": "Cinque domande, circa sei minuti. Il tuo coach ti mostra cosa funziona già.",
    "Focus": "Focus",
    "For a real application? (optional)": "Per una candidatura vera? (facoltativo)",
    "From your story bank": "Dalla tua raccolta di storie",
    "From your teacher. You can add it later.": "Dal tuo/dalla tua docente. Puoi aggiungerlo più tardi.",
    "General practice": "Allenamento generale",
    "Give an example": "Fai un esempio",
    "Good questions to ask:": "Buone domande da fare:",
    "Goodbye": "Ciao",
    "Guess first - then compare with your coach. This trains your inner judge.": "Prima stima – poi confronta con il coach. Così alleni il tuo giudizio interiore.",
    "Headline first: answer any question in one sentence, then add one reason. Practise with a timer (30 s).": "Prima il messaggio chiave: rispondere a ogni domanda in una frase, poi aggiungere un motivo. Esercitarsi con un timer (30 s).",
    "Hello {name}!": "Ciao {name}!",
    "Hide": "Nascondi",
    "Hide answers": "Nascondi risposte",
    "Hide example": "Nascondi esempio",
    "Hide hint": "Nascondi suggerimento",
    "Hint": "Suggerimento",
    "Hobbies": "Hobby",
    "How confident do you feel about job interviews now?": "Quanto ti senti sicuro/a ora nei colloqui di lavoro?",
    "How confident do you feel about job interviews right now?": "Quanto ti senti sicuro/a in questo momento nei colloqui di lavoro?",
    "How did that answer go?": "Com'è andata questa risposta?",
    "How far you've come": "Quanta strada hai fatto",
    "How it could sound": "Potrebbe suonare così",
    "How it helps in the job": "Come aiuta nel lavoro",
    "I'm a student": "Sono allievo/a",
    "I'm a teacher": "Sono docente",
    "I'm stuck - give me a hint": "Sono bloccato/a – dammi un suggerimento",
    "In {n} days": "Tra {n} giorni",
    "Interested": "Interessato/a",
    "Interview": "Colloquio",
    "Interview at {company}": "Colloquio presso {company}",
    "Interview coach for your apprenticeship": "Coach di colloquio per il tuo tirocinio",
    "Interview completed": "Colloquio completato",
    "Interview date": "Data del colloquio",
    "Interview finished!": "Colloquio finito!",
    "Interview in progress": "Colloquio in corso",
    "Interview language": "Lingua del colloquio",
    "Interview training for apprenticeships": "Allenamento ai colloqui per il tirocinio",
    "Interviewer": "Intervistatore/trice",
    "Introduction": "Presentazione",
    "It's okay to call politely and ask about the status of your application.": "Va benissimo chiamare gentilmente per chiedere a che punto è la tua candidatura.",
    "Job ad text": "Testo dell'annuncio",
    "Join class": "Unisciti alla classe",
    "Just for you - we'll ask again afterwards so you can see the difference.": "Solo per te – te lo chiediamo di nuovo dopo, così vedi la differenza.",
    "Keep track of every company - from trial days to the offer. Drag cards to change their stage.": "Tieni d'occhio ogni azienda – dallo stage alla conferma. Trascina le schede per cambiarne la fase.",
    "Language of the app": "Lingua dell'app",
    "Last practice": "Ultimo allenamento",
    "Leave class": "Lascia la classe",
    "Leave interview": "Lascia il colloquio",
    "Leave - you can continue later": "Esci – puoi continuare più tardi",
    "Length": "Durata",
    "Let my teacher read my interview answers": "Il/la mio/a docente può leggere le mie risposte",
    "Let's pause for a moment": "Facciamo una piccola pausa",
    "Like the real interview: no tips in between. Your full feedback waits in your summit log at the end.": "Come nel colloquio vero: nessun consiglio nel mezzo. Tutto il feedback ti aspetta alla fine nel tuo libro di vetta.",
    "Like the real thing - feedback at the end": "Come dal vero – feedback alla fine",
    "Made for the classroom": "Pensato per la classe",
    "Mode": "Modalità",
    "Motivation": "Motivazione",
    "Moved to {s}": "Spostata in {s}",
    "My apprenticeships": "I miei tirocini",
    "My class": "La mia classe",
    "Name the strength": "Indica il punto di forza",
    "Nervous? Try this:": "Nervoso/a? Prova così:",
    "New attempt - use the coach's tip.": "Nuovo tentativo – usa il consiglio del coach.",
    "New code": "Nuovo codice",
    "Next drill": "Prossimo allenamento",
    "Next time:": "La prossima volta:",
    "No drills due": "Nessun allenamento lampo da fare",
    "No e-mail needed. Letters, digits, dot or dash.": "Nessuna e-mail necessaria. Lettere, cifre, punto o trattino.",
    "No interviews yet.": "Ancora nessun colloquio.",
    "No reply from {company} for {n} days.": "Nessuna risposta da {company} da {n} giorni.",
    "No students yet": "Ancora nessun allievo",
    "Not enough answers for a profile yet.": "Non ci sono ancora abbastanza risposte per un profilo.",
    "Not great": "Non benissimo",
    "Notes": "Note",
    "Nothing due. A good day for a full practice interview.": "Niente in programma. Una buona giornata per un colloquio di prova completo.",
    "Now vs. your first interview": "Ora vs il tuo primo colloquio",
    "Offer": "Conferma",
    "Offline demo coach": "Coach demo offline",
    "Okay": "Così così",
    "Open": "Apri",
    "Open my summit log": "Apri il mio libro di vetta",
    "Overall score over time": "Punteggio complessivo nel tempo",
    "Pair work: each student tells a 60-second story using Situation → what I did → result. Partner asks 'and what did YOU do?'.": "Lavoro a coppie: ogni allievo racconta una storia di 60 secondi secondo Situazione → cosa ho fatto → risultato. Il/la compagno/a chiede «E TU cosa hai fatto?».",
    "Password": "Password",
    "Paste a job ad to tailor the questions (optional)": "Incolla un annuncio per adattare le domande (facoltativo)",
    "Paste it here - your rehearsal will ask about it.": "Incollalo qui – la tua prova generale farà domande su questo.",
    "Paste the text of the apprenticeship ad here…": "Incolla qui il testo dell'annuncio di tirocinio…",
    "Powered by Apertus (EPFL · ETH Zurich · CSCS)": "Basato su Apertus (EPFL · ETH Zurich · CSCS)",
    "Practice interview": "Colloquio di prova",
    "Practice sessions per week": "Sessioni a settimana",
    "Practice that sticks": "Pratica che resta",
    "Practise again": "Allenati ancora",
    "Practise your apprenticeship interview as often as you like - in German, French, Italian or Swiss German. An AI interviewer asks real questions, a coach shows you what already works and what to try next.": "Allenati al colloquio per il tirocinio quante volte vuoi – in tedesco, francese, italiano o svizzero tedesco. Un'IA ti fa domande vere, un coach ti mostra cosa funziona già e cosa provare dopo.",
    "Preferred interview language": "Lingua preferita per il colloquio",
    "Previous session": "Sessione precedente",
    "Print / PDF": "Stampa / PDF",
    "Profile & privacy": "Profilo & privacy",
    "Profile saved": "Profilo salvato",
    "Progress": "Progressi",
    "Rate your answers before the feedback appears - after 3 ratings you'll see how well you judge yourself.": "Valuta le tue risposte prima del feedback – dopo 3 valutazioni vedrai quanto bene ti giudichi.",
    "Ready for a practice round?": "Pronto/a per un giro di prova?",
    "Rehearse exactly this interview - with questions about this company and its job ad.": "Prova esattamente questo colloquio – con domande su questa azienda e il suo annuncio.",
    "Rehearse interview": "Prova il colloquio",
    "Rehearse this interview": "Prova questo colloquio",
    "Rehearsed {n}×": "Provato {n}×",
    "Rejected": "Rifiuto",
    "Relevance": "Pertinenza",
    "Remove": "Rimuovi",
    "Removed": "Rimosso",
    "Result / what you learned": "Risultato / cosa hai imparato",
    "Role play greetings and closings: handshake, 'Grüezi Frau…', full sentences, thanking at the end.": "Gioco di ruolo saluti e congedo: stretta di mano, «Buongiorno signora…», frasi complete, ringraziare alla fine.",
    "Rule-based stand-in. Connect Apertus for real feedback.": "Sostituto basato su regole. Collega Apertus per un feedback vero.",
    "Powered by Apertus, Switzerland's open language model. No e-mail needed. This demo is hosted on Google Cloud; schools can also run it on their own server.": "Basato su Apertus, il modello linguistico aperto svizzero. Nessuna e-mail necessaria. Questa demo usa Google Cloud; le scuole possono usare il proprio server.",
    "Save": "Salva",
    "Save profile": "Salva profilo",
    "Saved": "Salvato",
    "School": "Scuola",
    "School / class": "Scuola / classe",
    "Score profile": "Profilo dei punteggi",
    "Scores and activity of your students. Answer texts are only visible if a student agrees.": "Punteggi e attività dei suoi allievi. I testi delle risposte sono visibili solo con il consenso dell'allievo.",
    "Self-assessment": "Autovalutazione",
    "Self-awareness": "Consapevolezza di sé",
    "Send (Ctrl+Enter)": "Invia (Ctrl+Invio)",
    "Send answer": "Invia risposta",
    "Sessions": "Sessioni",
    "Set up your interview": "Prepara il colloquio",
    "Share the class code {code} with your students.": "Condivida il codice della classe {code} con i suoi allievi.",
    "Short": "Breve",
    "Short real moments you can use as examples: a problem you solved, a time you helped someone. The hint button reminds you of them during interviews.": "Brevi momenti reali da usare come esempi: un problema che hai risolto, una volta che hai aiutato qualcuno. Il pulsante suggerimento te li ricorda durante il colloquio.",
    "Show answers": "Mostra risposte",
    "Sign in": "Accedi",
    "Sign out": "Esci",
    "Situation": "Situazione",
    "Situations": "Situazioni",
    "Skip and show feedback": "Salta e mostra il feedback",
    "Something went wrong - try again.": "Qualcosa è andato storto – riprova.",
    "Spaced practice · drill boxes": "Pratica distribuita · scatole di allenamento",
    "Start interview": "Inizia il colloquio",
    "Start practice interview": "Inizia un colloquio di prova",
    "Start practising": "Inizia ad allenarti",
    "Status": "Stato",
    "Stop for today": "Basta per oggi",
    "Story bank": "Raccolta di storie",
    "Strength bingo: students collect three strengths from classmates, each with a moment they observed it.": "Bingo dei punti di forza: gli allievi raccolgono tre punti di forza dai compagni, ognuno con un momento in cui è stato osservato.",
    "Strengths": "Punti di forza",
    "Strong": "Ottimo",
    "Strong:": "Ottimo:",
    "Student": "Allievo/a",
    "Students join with a 6-letter code - no e-mail addresses needed.": "Gli allievi entrano con un codice di 6 lettere – senza indirizzi e-mail.",
    "Students × criteria (last 3 interviews)": "Allievi × criteri (ultimi 3 colloqui)",
    "Summit log": "Libro di vetta",
    "Summit points per interview": "Punti vetta per colloquio",
    "Swiss and private": "Svizzero e privato",
    "Teachers see who practised and where the class struggles - transcripts only if a student agrees. Fits the career-choice lessons of Lehrplan 21.": "I docenti vedono chi si è allenato e dove la classe fa fatica – trascrizioni solo con il consenso dell'allievo. Si integra nelle lezioni di scelta professionale del Lehrplan 21.",
    "The coach did not answer - try again.": "Il coach non ha risposto – riprova.",
    "The next interviews will train these on purpose:": "I prossimi colloqui alleneranno apposta:",
    "This permanently deletes your account, interviews, drills and apprenticeships. It cannot be undone.": "Questo elimina definitivamente il tuo account, i colloqui, gli allenamenti e i tirocini. Non si può annullare.",
    "This session": "Questa sessione",
    "Today": "Oggi",
    "Tough round? That's normal. The next one usually feels easier.": "Giro difficile? È normale. Il prossimo di solito sembra più facile.",
    "Town": "Località",
    "Training": "Allenamento",
    "Trial apprenticeship": "Stage di orientamento",
    "Trial apprenticeships & experience": "Stage & esperienze",
    "Trial-day debrief: each student writes 3 sentences 'What surprised me in my Schnupperlehre and why I want this job'.": "Bilancio dello stage: ogni allievo scrive 3 frasi «Cosa mi ha sorpreso durante lo stage e perché voglio questo mestiere».",
    "Try as student": "Prova come allievo/a",
    "Try as teacher": "Prova come docente",
    "Try next": "Da provare",
    "Try the coach": "Prova il coach",
    "Try this answer again": "Riprova questa risposta",
    "Turn on the interviewer's voice": "Attiva la voce dell'intervistatore",
    "Undo": "Annulla",
    "Username": "Nome utente",
    "Vocational trainer · Pflegezentrum Calanda, Chur": "Formatrice · Pflegezentrum Calanda, Coira",
    "Voice on - the interviewer speaks": "Voce attiva – l'intervistatore parla",
    "Waiting for an answer": "In attesa di risposta",
    "Welcome!": "Benvenuto/a!",
    "What YOU did": "Cosa hai fatto TU",
    "What already works": "Cosa funziona già",
    "What connects you to this job?": "Cosa ti lega a questo mestiere?",
    "What do you enjoy doing?": "Cosa ti piace fare?",
    "What does a typical day look like?": "Com'è una giornata tipo?",
    "What worked": "Cosa ha funzionato",
    "When will you decide?": "Quando prenderete una decisione?",
    "Where did you do a Schnupperlehre? What did you do there?": "Dove hai fatto uno stage? Cosa hai fatto lì?",
    "Where the class struggles - and a lesson idea": "Dove la classe fa fatica – e un'idea per la lezione",
    "Who are you?": "Chi sei?",
    "Why this company": "Perché questa azienda",
    "You are in": "Sei in",
    "You feel more confident than before. That's what practice does.": "Ti senti più sicuro/a di prima. È l'effetto dell'allenamento.",
    "You joined {name}": "Sei entrato/a in {name}",
    "You judge yourself realistically - a real skill for interviews.": "Ti valuti in modo realistico – una vera abilità per i colloqui.",
    "You rated yourself a bit higher than the coach did.": "Ti sei valutato/a un po' più in alto del coach.",
    "You tend to rate yourself higher than the coach. Check: did you give a concrete example?": "Tendi a valutarti più in alto del coach. Controlla: hai fatto un esempio concreto?",
    "You were stricter with yourself than the coach - it went better than you thought!": "Sei stato/a più severo/a con te del coach – è andata meglio di quanto pensassi!",
    "You're stricter with yourself than the coach. You're better than you think!": "Sei più severo/a con te del coach. Sei più bravo/a di quanto pensi!",
    "You've rehearsed this one {n}× - best score {s}.": "Hai provato questo colloquio {n}× – miglior punteggio {s}.",
    "Your answer": "La tua risposta",
    "Your answer…": "La tua risposta…",
    "Your coach": "Il tuo coach",
    "Your coach is writing your feedback…": "Il tuo coach sta scrivendo il feedback…",
    "Your confidence is stable - keep going, it grows with repetition.": "La tua fiducia è stabile – continua, cresce con la ripetizione.",
    "Your data": "I tuoi dati",
    "Your focus": "Il tuo focus",
    "Your guess matched the coach - good self-assessment!": "La tua stima coincide con quella del coach – buona autovalutazione!",
    "Your interview as a trail: height = score per answer": "Il tuo colloquio come sentiero: altitudine = punteggio per risposta",
    "Your interviewer uses this to ask personal questions. Share only what you're comfortable with - no addresses or phone numbers needed.": "Il tuo intervistatore lo usa per fare domande personali. Condividi solo ciò che ti va – non servono indirizzi né numeri di telefono.",
    "Your next stage": "La tua prossima tappa",
    "Your path to an offer": "La tua strada verso un posto",
    "Your profile": "Il tuo profilo",
    "Your questions": "Le tue domande",
    "Your reason": "Il tuo motivo",
    "Your teacher always sees scores and how often you practise. Your actual answers only if you tick this. You can change it any time.": "Il/la tuo/a docente vede sempre i punteggi e quanto spesso ti alleni. Le tue risposte solo se spunti qui. Puoi cambiarlo in qualsiasi momento.",
    "Your trail starts with the first interview": "Il tuo sentiero inizia con il primo colloquio",
    "Your weakest answers are now 2-minute drills": "Le tue risposte più deboli ora sono allenamenti lampo di 2 minuti",
    "Zusage runs on Apertus, the open Swiss language model, on this server. Your answers are not used to train any model. Answer texts are deleted automatically after 180 days; scores stay for your progress.": "Zusage funziona con Apertus, il modello linguistico aperto svizzero, su questo server. Le tue risposte non vengono usate per addestrare modelli. I testi delle risposte vengono eliminati automaticamente dopo 180 giorni; i punteggi restano per i tuoi progressi.",
    "a real moment from your trial apprenticeship - that is convincing.": "un momento vero del tuo stage – è convincente.",
    "about 15 min": "circa 15 min",
    "about 6 min": "circa 6 min",
    "add what YOU learned from it, e.g. patience.": "aggiungi cosa hai imparato TU, p. es. la pazienza.",
    "after": "dopo",
    "answer": "risposta",
    "backup coach": "coach di riserva",
    "before": "prima",
    "best": "migliore",
    "confidence per session": "fiducia per sessione",
    "day streak": "giorni di fila",
    "due": "da fare",
    "e.g. Sek A, 3rd year": "p. es. 4a media",
    "follow-up": "domanda di approfondimento",
    "has an offer": "ha un posto",
    "have an offer": "hanno un posto",
    "interview soon": "colloquio a breve",
    "interviews": "colloqui",
    "last score": "ultimo punteggio",
    "low confidence": "poca fiducia",
    "model calls": "chiamate al modello",
    "more interviews coming up": "altri colloqui in arrivo",
    "need a nudge": "hanno bisogno di una spinta",
    "no data": "nessun dato",
    "not practising": "non si allena",
    "of 100 summit points": "su 100 punti vetta",
    "of your guesses matched the coach ({n} answers).": "delle tue stime coincidevano con il coach ({n} risposte).",
    "per answer": "per risposta",
    "practised this week": "si sono allenati questa settimana",
    "questions": "domande",
    "second attempt": "secondo tentativo",
    "shares answers with you": "condivide le risposte con lei",
    "students": "allievi",
    "very confident": "molto sicuro/a",
    "very nervous": "molto nervoso/a",
    "vs. last time": "vs l'ultima volta",
    "with job ad": "con annuncio",
    "{name} is listening…": "{name} ascolta…",
    "{n} short drills are waiting - about {m} minutes.": "{n} allenamenti lampo ti aspettano – circa {m} minuti.",
  },
};
